#!/usr/bin/env python

import os

# from flask import url_for

from flask.ext.script import Manager
from flask.ext.script import Shell

from flask.ext.script.commands import ShowUrls

from reppo import create_app

if 'LANG' not in os.environ:
    os.environ['LANG'] = 'en_US.UTF-8'

_BANNER = '''
    ____                         __
   / __ \___  ____  ____  ____  / /
  / /_/ / _ \/ __ \/ __ \/ __ \/ /
 / _, _/  __/ /_/ / /_/ / /_/ /_/
/_/ |_|\___/ .___/ .___/\____(_)
          /_/   /_/
'''

manager = Manager(create_app, with_default_commands=False)
manager.add_option('-c', '--config', dest='config')


def _make_context():
    return dict(
        app=manager.app,
    )


manager.add_command('shell', Shell(banner=_BANNER, make_context=_make_context))
manager.add_command('urls', ShowUrls())


if __name__ == '__main__':
    manager.run()
