#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

from werkzeug import script

if 'LANG' not in os.environ:
    os.environ['LANG'] = 'en_US.UTF-8'

_BANNER = '''
    ____                         __
   / __ \___  ____  ____  ____  / /
  / /_/ / _ \/ __ \/ __ \/ __ \/ /
 / _, _/  __/ /_/ / /_/ / /_/ /_/
/_/ |_|\___/ .___/ .___/\____(_)
          /_/   /_/
'''


def make_app():
    from reppo import create_app
    return create_app()


def make_shell():
    app = make_app()
    repo = app.config['REPOS']['tablet']
    return locals()

action_runserver = script.make_runserver(make_app, use_reloader=True)
action_shell = script.make_shell(make_shell, banner=_BANNER)

# example how to add our own actions
# action_initdb = lambda: make_app().init_database()

if __name__ == '__main__':
    script.run()
